version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: "@quasar/app"
    versions:
    - 2.2.3
  - dependency-name: "@quasar/extras"
    versions:
    - 1.10.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
